permalink: pretty;
theme: "jekyll_patternbot"

patternbot:
  font_url: <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans:400,400i,700|Source+Code+Pro:400,700&display=swap" rel="stylesheet">
